//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WClust.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_WCLUST_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_WCLUSTTYPE                  129
#define IDD_EDITDIALOG                  130
#define IDD_RANGEDIALOG                 137
#define IDD_EDIT_SPIKES                 138
#define IDD_SELECT_TETRODE              140
#define IDD_DIALLIST                    141
#define IDD_TIME_EV                     146
#define IDD_POSITION_REG_DLG            149
#define IDB_0000FF                      152
#define IDB_00FF00                      153
#define IDB_FF0000                      154
#define IDB_009090                      155
#define IDB_909000                      156
#define IDB_900090                      157
#define IDB_909090                      158
#define IDB_00F0F0                      159
#define IDB_F0F000                      160
#define IDB_F000F0                      161
#define IDB_0090F0                      162
#define IDB_9000F0                      163
#define IDB_00F090                      164
#define IDB_90F000                      165
#define IDB_F00090                      166
#define IDB_F09000                      167
#define IDB_9090F0                      168
#define IDB_90F090                      169
#define IDB_F09090                      170
#define IDD_CHOOSE_VERX_DLG             171
#define IDB_000000                      172
#define IDD_CHOOSE_WCP_DLG              173
#define IDD_DLG_WCP_NOT_FOUND           174
#define IDD_DLG_INFO                    175
#define IDB_CCCCCC                      176
#define IDD_BINDIALOG                   177
#define IDD_DLG_CLUST_NUM               180
#define IDD_DIALOG_APS                  181
#define IDD_DIALOG_SHOW_SPIKE_XY        182
#define IDD_KM_DIALOG                   183
#define IDD_DIALOG_ECLUST               184
#define IDD_PROGRESS_DIALOG             185
#define IDD_DIALOG_AUTOC_PROG           186
#define IDD_DLG_RATE                    187
#define IDD_DLG_AUTO_DENOISE            189
#define IDD_DIALOG1                     191
#define IDD_DIALOG_EEG_GAINS            191
#define IDD_DIALOG_SAMPLE_BATCH         192
#define IDD_DIALOG_KLD_DLG_OPT          193
#define IDD_DIALOG_VID                  194
#define IDD_DIALOG_FL                   195
#define IDD_DIALOG_NOTES                196
#define IDD_SOM_DLG                     197
#define IDD_DIALOG_KLUSTAKWIK           198
#define IDC_LISTVX                      1001
#define IDC_COMBOCLUST                  1003
#define IDC_NEWPOLY                     1004
#define IDC_EDITPOLY                    1005
#define IDC_REMOVEPOLY                  1006
#define IDC_HIDEPOLY                    1007
#define IDC_SHOWPOLY                    1008
#define IDC_DRAWPOLY                    1009
#define IDC_HIDEPNTS                    1010
#define IDC_SHOWPNTS                    1011
#define IDC_REMALLPOLY                  1012
#define IDC_UNDOLAST                    1013
#define IDC_BUTTON1                     1018
#define IDC_APPLY                       1018
#define IDC_SETTINGS                    1018
#define IDC_ADD_V                       1018
#define IDC_BUTTON2                     1019
#define IDC_DRAW_SPIKES                 1019
#define IDC_BUT_SET                     1019
#define IDC_PLAY                        1019
#define IDC_ADD_PARAM                   1019
#define IDC_BUTTON3                     1020
#define IDC_STOP                        1020
#define IDC_SET_SPIKES                  1020
#define IDC_BUTTON4                     1021
#define IDC_NEXT                        1021
#define IDC_INITVIEW                    1021
#define IDC_COMBO1                      1022
#define IDC_CMB_UNIT                    1022
#define IDC_CMB_ORIG_NEW                1022
#define IDC_COMBO_RATE                  1022
#define IDC_COMBO_LOW_SAT               1022
#define IDC_COMBO_EEG_GAIN_CHAN         1022
#define IDC_COMBO_FL_DTT                1022
#define IDC_SPIN_Y                      1023
#define IDC_SPIN_X                      1024
#define IDC_EDIT_MINY                   1025
#define IDC_EDIT_MAXY                   1026
#define IDC_EDIT_MINX                   1027
#define IDC_EDIT_MAXX                   1028
#define IDC_ZOOMIN                      1029
#define IDC_FitView                     1030
#define IDC_FIT_VIEW                    1030
#define IDC_COPYCLUSTER                 1031
#define IDC_COMBOPEN                    1032
#define IDC_SPIN_SPIKES                 1038
#define IDC_EDIT_FIRST_EV               1039
#define IDC_EDIT_LAST_EV                1040
#define IDC_EDIT_PERCENT                1041
#define IDC_COMBOPROP                   1046
#define IDC_ADD_DV                      1047
#define IDC_CHECK_CH1                   1048
#define IDC_CHECK_CH2                   1049
#define IDC_CHECK_CH3                   1050
#define IDC_CHECK_CH4                   1051
#define IDC_CMB_SP_CLUST                1052
#define IDC_REMOVE                      1053
#define IDC_SET_SP                      1055
#define IDC_CHECKFIT                    1056
#define IDC_RADIO1                      1058
#define IDC_RADIO_SYNC                  1058
#define IDC_RADIO_XY_8                  1058
#define IDC_RADIO_1D_SLICE              1058
#define IDC_RADIO2                      1059
#define IDC_RADIO_CONST                 1059
#define IDC_RADIO_GOOD                  1059
#define IDC_RADIO_XY_4                  1059
#define IDC_RADIO_2D_SLICES             1059
#define IDC_RADIO3                      1060
#define IDC_RADIO_OTHER                 1060
#define IDC_RADIO_XY_2                  1060
#define IDC_RADIO4                      1061
#define IDC_RADIO_WITHOUT               1061
#define IDC_RADIO_XY_16                 1061
#define IDC_ORIG_NEW                    1064
#define IDC_CMB_SEL_PARAM               1065
#define IDC_ADD                         1066
#define IDC_RD_RANDOM                   1067
#define IDC_RD_EXCLUDE                  1068
#define IDC_RD_WEIGHTED                 1069
#define IDC_LIST                        1070
#define IDC_LIST1                       1071
#define IDC_BUTTON5                     1073
#define IDC_BUTTON6                     1074
#define IDC_BUTTON7                     1075
#define IDC_SHOW                        1076
#define IDC_HIDE                        1077
#define IDC_BCLEAR                      1078
#define IDC_BSHOWALL                    1079
#define IDC_BRESET                      1080
#define IDC_CHECK1                      1081
#define IDC_CHECK_GOOD                  1081
#define IDC_CHECK_SPIKE_XY              1081
#define IDC_CHECK_PCA                   1081
#define IDC_CHECK_FAST_KLD              1081
#define IDC_CHECK_ELUT                  1081
#define IDC_CHECK_KM_NORMALIZE          1081
#define IDC_CHECK2                      1082
#define IDC_CHECK_ROOM                  1082
#define IDC_CHECK_FAIR                  1082
#define IDC_CHECK_PCA_CONCAT            1082
#define IDC_CHECK_INTER_KLD             1082
#define IDC_CHECK_KM_MEDIANS            1082
#define IDC_LIST_OF_ELECTRODES          1083
#define IDC_CHECK_POOR                  1083
#define IDC_ED_AMOUNT                   1084
#define IDC_PERBUT1                     1091
#define IDC_PERBUT2                     1093
#define IDC_PERBUT3                     1094
#define IDC_PERBUT4                     1095
#define IDC_PERBUT5                     1096
#define IDC_PERBUT6                     1097
#define IDC_BUT_UNDO                    1099
#define IDC_TIME_EV                     1100
#define IDC_SCROLL_TIME                 1107
#define IDC_SPIN_TIME                   1110
#define IDC_EDIT_TIME                   1111
#define IDC_CHECK_RASTER                1116
#define IDC_CHECK_SPIKE                 1117
#define IDC_16_7                        1121
#define IDC_20                          1122
#define IDC_33_3                        1123
#define IDC_40                          1124
#define IDC_100                         1125
#define IDC_EDIT                        1126
#define IDC_LIST_SCALE                  1127
#define IDC_LIST_ARENA_CL               1128
#define IDC_LIST_ROOM_CL                1129
#define IDC_LIST_SPIKE_CL               1130
#define IDC_CMB_ROOM                    1131
#define IDC_CMB_ARENA                   1132
#define IDC_TE_PLAY                     1133
#define IDC_TE_CLEAR                    1134
#define IDC_MAX                         1135
#define IDC_TE_TAKE_PICT                1136
#define IDC_EXPAND                      1137
#define IDC_LIST_VERX                   1138
#define IDC_LIST_PNTS                   1139
#define IDC_CMB_ORIG_NEW1               1142
#define IDC_EXT_PARAM                   1143
#define IDC_REFRESH                     1144
#define IDC_LIST_CHOOSEN                1145
#define IDC_LIST_POSSIBLE               1146
#define IDC_EDIT_FILE_NAME              1148
#define IDC_EDIT_SYNC                   1149
#define IDC_LIST_USED                   1150
#define IDC_EDIT_ARENA                  1151
#define IDC_EDIT_ROOM                   1152
#define IDC_LIST_FOUND                  1153
#define IDC_LIST_CLUST                  1154
#define IDC_LIST_MESSAGE                1155
#define IDC_EDIT1                       1157
#define IDC_EDIT_CLUST_NUMS             1158
#define IDC_EDIT_KK_MAXCLUSTS           1158
#define IDC_MAKE_NOISE_BTN              1159
#define IDC_EDIT_AP_CLUST               1160
#define IDC_EDIT_SHOW_SPIKES_XY         1161
#define IDC_EDIT_KM                     1162
#define IDC_EDIT_ECLUST                 1164
#define IDC_PROGRESS_BAR                1165
#define IDC_PROGRESS_TEXT               1166
#define IDC_BUTTON_RATE                 1168
#define IDC_RADIO_XY_32                 1169
#define IDC_EDIT_NUM_PCS                1170
#define IDC_COMBO_HIGH_SAT              1174
#define IDC_COMBO3                      1175
#define IDC_COMBO_FRAC_SAT              1175
#define IDC_BUTTON_CINF                 1176
#define IDC_BUTTON_SET_GAINS            1177
#define IDC_EDIT_EEG_GAIN               1178
#define IDC_EDIT_BATCH_SAMP_TXT         1181
#define IDC_STATIC_SAMP_B_TXT           1182
#define IDC_CHECK3                      1184
#define IDC_CHECK_LD_EEG                1184
#define IDC_CHECK_ISOLATION_D           1184
#define IDC_SPINNNKLD                   1185
#define IDC_EDITNNKLD                   1186
#define IDC_STATIC_K                    1187
#define IDC_CHECK_KLD_DO                1188
#define IDC_SPINEEGPLAYSPEED            1189
#define IDC_EDITEEGPLAYSPEED            1191
#define IDC_SPINEEGGAIN                 1193
#define IDC_EDITEEGGAIN                 1194
#define IDC_STATIC_EEG_GAIN             1195
#define IDC_BUTTON_PICK_VID             1197
#define IDC_BUTTON_VID_DLG_OPEN         1198
#define IDC_EDIT_VID_OFFSET             1199
#define IDC_EDIT_SET_TIME               1200
#define IDC_BUTTON_SET_TIME             1201
#define IDC_CHECK_FIND_BEST_DIMS        1202
#define IDC_EDIT_BEST_DIMS              1203
#define IDC_BUTTON_SET_NUM_BEST_DIMS    1206
#define IDC_CHECK_SILHOUETTE_WIDTH      1207
#define IDC_CHECK_NORM                  1208
#define IDC_CHECK_LRATIO                1209
#define IDC_EDIT_EXTRA_PARAM            1210
#define IDC_STATIC_EXTRA_PARAM          1211
#define IDC_EDIT_EMINC                  1212
#define IDC_EDIT_EMAXC                  1213
#define IDC_STATIC_EMINC                1214
#define IDC_STATIC_EMAXC                1215
#define IDC_STATIC_ENITER               1216
#define IDC_EDIT_ENUMITER               1217
#define IDC_STATIC_ENCITERS             1218
#define IDC_EDIT_ENUMITER2              1219
#define IDC_EDIT_ERR_PRCT_E             1221
#define IDC_EDIT_KM_MAXC                1222
#define IDC_EDIT_KM_MINC                1223
#define IDC_EDIT3                       1224
#define IDC_EDIT_KM_NITERS              1224
#define IDC_EDIT_KNNFL                  1224
#define IDC_EDIT_ANIMAL_WEIGHT          1224
#define IDC_EDIT_KK_START_ITERS         1224
#define IDC_EDIT4                       1225
#define IDC_EDIT_KK_MAX_POSSIBLE_CLUSTERS 1225
#define IDC_EDIT_EPS_FL                 1226
#define IDC_EDIT_IN1_AMOUNT             1226
#define IDC_STATIC_DT                   1227
#define IDC_EDIT_IN2_TYPE               1227
#define IDC_EDIT_ITER_FL                1228
#define IDC_EDIT10                      1228
#define IDC_STATIC_THD_FL               1229
#define IDC_EDIT_IN3_TYPE               1229
#define IDC_EDIT_OUT_FL                 1230
#define IDC_EDIT14                      1230
#define IDC_EDIT_ANIMAL_AGE             1231
#define IDC_EDIT_IN1_TIME               1232
#define IDC_EDIT_IN1_LOC                1233
#define IDC_EDIT_IN2_TIME               1234
#define IDC_EDIT_IN2_LOC                1235
#define IDC_EDIT_IN3_TIME               1236
#define IDC_EDIT_IN3_LOC                1237
#define IDC_EDIT_IN4_TYPE               1238
#define IDC_EDIT_IN4_TIME               1239
#define IDC_EDIT18                      1240
#define IDC_EDIT_IN4_LOC                1241
#define IDC_EDIT_EXP_COMMENTS           1242
#define IDC_MONTHCALENDAR_EXP_DATE      1243
#define IDC_EDIT_ANIMAL_SEX             1244
#define IDC_EDIT_ANIMAL_DETAILS         1245
#define IDC_EDIT_ANIMAL_TYPE            1246
#define IDC_EDIT_IN1_TYPE               1247
#define IDC_EDIT_ITER_SOM               1248
#define IDC_EDIT_XG_SOM                 1249
#define IDC_CHECK_KLD_DEFAULT_DIMS      1249
#define IDC_EDIT_YG_SOM                 1250
#define IDC_EDIT_MIN_SPIKE_AMP          1250
#define IDC_EDIT_ITAU_SOM               1251
#define IDC_EDIT_KK_MINCLUSTS           1252
#define ID_FILE_OPENBPFILE              32771
#define ID_EDITDLG                      32772
#define IDC_NEWCLUST                    32773
#define ID_FILE_SAVECLUSTERS            32774
#define ID_FILE_LOADCLUSTERS            32775
#define ID_BUTTON32776                  32776
#define ID_FILE_STORETOBPFILE           32781
#define ID_ENVIRONMENT_OPEN             32782
#define ID_ENVIRONMENT_SAVE             32783
#define ID_ENVIRONMENT_LOAD             32784
#define ID_NEWCLUST                     32785
#define ID_LOAD_ARENA                   32788
#define ID_LOAD_ROOM                    32789
#define ID_FILE_STORETOFILE             32791
#define ID_MODE_SWAPPOLARITY            32792
#define ID_POS_REG_WIN                  32793
#define ID_TIME_EV_WIN                  32794
#define ID_TOOLS_INFO                   32795
#define ID_TOOLS_EXPORT                 32796
#define ID_CLUSTER_SETBINS              32797
#define ID_CLUSTER_HI                   32798
#define ID_TOOLS_HMM                    32799
#define ID_CLUSTER_SETBINS32800         32800
#define ID_CLUSTER_INFOCLUST            32801
#define ID_CLUSTER_K                    32802
#define ID_CLUSTER_RESISTORINFOCLUST    32803
#define ID_CLUSTER_APCLUST              32804
#define ID_CLUSTER_KLUSTAKWIKCLUST      32805
#define ID_TOOLS_VIEWSPIKEROOMX         32807
#define ID_CLUSTER_USERSPIKEX           32808
#define ID_CLUSTER_USERSPIKEXY          32809
#define ID_CLUSTER_USE_SPIKEXY          32810
#define ID_CLUSTER_ENTROPYINFOCLUST     32811
#define ID_TOOLS_AUTOFINDNOISE          32813
#define ID_Menu                         32814
#define ID_BATCH_QUALITYRUN             32815
#define ID_BATCH_SAMPLEBATCHFILE        32816
#define ID_CLUSTER_SETKLDOPTIONS        32817
#define ID_TOOLS_EXPORTSPIKES           32818
#define ID_CLUSTER_CALCCLUSTERQUALITY   32819
#define ID_TOOLS_EXPORTHQPC1            32820
#define ID_TOOLS_IMPORTSPIKES           32821
#define ID_BATCH_TIMESTAMPADJUST        32822
#define ID_CLUSTER_FLAMECLUSTERING      32823
#define ID_CLUSTER_SOMCLUSTERING        32824
#define ID_BATCH_AUTOCLUSTERING         32825
#define ID_TOOLS_EXPORTCLUSTERBOUNDS    32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
